// import { v4 as uuid } from "uuid";

export const recipesData = [
  {
    _id: "b481c9a7-68db-4add-92ba-ce46cf6b0116",
    id: 1,
    name: "Spaghetti Bolognese",
    ingredients: [
      "250g spaghetti",
      "400g ground beef",
      "1 onion, diced",
      "2 cloves of garlic, minced",
      "1 can (400g) crushed tomatoes",
      "1 tablespoon tomato paste",
      "1 teaspoon dried oregano",
      "1 teaspoon dried basil",
      "Salt and pepper to taste",
      "Grated Parmesan cheese for garnish",
    ],
    instructions: [
      "Cook the spaghetti according to package instructions.",
      "In a large skillet, brown the ground beef over medium heat.",
      "Add the diced onion and minced garlic to the skillet and cook until the onion is translucent.",
      "Stir in the crushed tomatoes, tomato paste, oregano, basil, salt, and pepper. Simmer for 20 minutes.",
      "Serve the sauce over the cooked spaghetti and garnish with grated Parmesan cheese.",
    ],
    cuisine: "Italian",
  },
  {
    _id: "d1ba4d56-5711-422c-930b-bbe520cda192",
    id: 2,
    name: "Chicken Curry",
    ingredients: [
      "500g chicken breast, cut into pieces",
      "1 onion, chopped",
      "2 cloves of garlic, minced",
      "1 tablespoon curry powder",
      "1 can (400ml) coconut milk",
      "1 tablespoon vegetable oil",
      "Salt and pepper to taste",
      "Fresh cilantro for garnish",
    ],
    instructions: [
      "Heat the vegetable oil in a large pan over medium heat.",
      "Add the chopped onion and minced garlic to the pan and cook until the onion is soft.",
      "Add the chicken pieces to the pan and cook until browned.",
      "Sprinkle the curry powder over the chicken and stir to coat.",
      "Pour in the coconut milk and simmer for 15-20 minutes, or until the chicken is cooked through.",
      "Season with salt and pepper to taste.",
      "Garnish with fresh cilantro before serving.",
    ],
    cuisine: "Indian",
  },
  {
    _id: "450b6c94-748f-40e5-a015-0b98ecfeec2f",
    id: 3,
    name: "Caprese Salad",
    ingredients: [
      "2 large tomatoes, sliced",
      "200g fresh mozzarella cheese, sliced",
      "1 bunch of fresh basil leaves",
      "2 tablespoons extra virgin olive oil",
      "Salt and pepper to taste",
      "Balsamic glaze for drizzling",
    ],
    instructions: [
      "Arrange the tomato slices and mozzarella slices on a serving platter.",
      "Tuck the fresh basil leaves in between the tomato and mozzarella slices.",
      "Drizzle the extra virgin olive oil over the salad.",
      "Season with salt and pepper to taste.",
      "Finish by drizzling balsamic glaze over the salad.",
      "Serve immediately.",
    ],
    cuisine: "Italian",
  },
  {
    _id: "7277236a-8e3d-4141-ae15-d5f7c8d79650",
    id: 4,
    name: "Butter Chicken",
    ingredients: [
      "500g boneless chicken, cut into pieces",
      "1 cup plain yogurt",
      "2 tablespoons butter",
      "1 onion, finely chopped",
      "2 cloves of garlic, minced",
      "1 tablespoon ginger paste",
      "1 teaspoon garam masala",
      "1 teaspoon turmeric powder",
      "1 teaspoon chili powder",
      "1 cup tomato puree",
      "1/2 cup heavy cream",
      "Salt to taste",
      "Fresh cilantro for garnish",
    ],
    instructions: [
      "Marinate the chicken pieces in yogurt for at least 1 hour.",
      "In a large pan, melt the butter over medium heat.",
      "Add the chopped onion, minced garlic, and ginger paste. Sauté until the onion turns golden brown.",
      "Add the marinated chicken and cook until it's no longer pink.",
      "Stir in the garam masala, turmeric powder, and chili powder. Mix well.",
      "Add the tomato puree and cook for another 10 minutes.",
      "Pour in the heavy cream and simmer for 5 minutes.",
      "Season with salt to taste.",
      "Garnish with fresh cilantro before serving.",
    ],
    cuisine: "Indian",
  },
  {
    _id: "6b6ee29c-46a8-4a1f-84ff-24c9bc57d101",
    id: 5,
    name: "Vegetable Biryani",
    ingredients: [
      "2 cups basmati rice",
      "1 cup mixed vegetables (carrots, peas, beans, etc.)",
      "1 onion, thinly sliced",
      "2 cloves of garlic, minced",
      "1 tablespoon ginger paste",
      "2 tablespoons ghee or vegetable oil",
      "1 teaspoon cumin seeds",
      "2 bay leaves",
      "4 green cardamom pods",
      "4 cloves",
      "1 cinnamon stick",
      "1 teaspoon turmeric powder",
      "1 teaspoon garam masala",
      "Salt to taste",
      "Fresh cilantro for garnish",
    ],
    instructions: [
      "Wash the basmati rice and soak it in water for 30 minutes. Drain and set aside.",
      "In a large pot, heat the ghee or vegetable oil over medium heat.",
      "Add the cumin seeds, bay leaves, cardamom pods, cloves, and cinnamon stick. Sauté for a minute.",
      "Add the sliced onion, minced garlic, and ginger paste. Sauté until the onion turns golden brown.",
      "Add the mixed vegetables and cook for a few minutes.",
      "Stir in the turmeric powder and garam masala.",
      "Add the soaked basmati rice to the pot and mix well with the vegetables and spices.",
      "Pour in enough water to cover the rice (about 4 cups) and season with salt.",
      "Bring the mixture to a boil, then reduce the heat to low and cover the pot with a tight-fitting lid.",
      "Cook for 15-20 minutes or until the rice is cooked and the water is absorbed.",
      "Garnish with fresh cilantro before serving.",
    ],
    cuisine: "Indian",
  },
  {
    _id: "6b9625b4-bf25-4b41-9f1d-5511faee45f9",
    id: 6,
    name: "Palak Paneer",
    ingredients: [
      "200g paneer, cubed",
      "2 bunches of spinach, washed and chopped",
      "1 onion, finely chopped",
      "2 tomatoes, pureed",
      "2 cloves of garlic, minced",
      "1 tablespoon ginger paste",
      "2 tablespoons ghee or vegetable oil",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "1 teaspoon garam masala",
      "1/2 cup heavy cream",
      "Salt to taste",
    ],
    instructions: [
      "In a large pan, heat the ghee or vegetable oil over medium heat.",
      "Add the cumin seeds and sauté until they start to crackle.",
      "Add the chopped onion, minced garlic, and ginger paste. Sauté until the onion turns golden brown.",
      "Add the pureed tomatoes and cook for a few minutes.",
      "Stir in the turmeric powder and garam masala.",
      "Add the chopped spinach and cook until wilted.",
      "Transfer the mixture to a blender or use an immersion blender to puree the spinach mixture until smooth.",
      "Return the pureed spinach mixture to the pan and bring it to a simmer.",
      "Add the cubed paneer and cook for a few minutes.",
      "Stir in the heavy cream and season with salt to taste.",
      "Simmer for another 5 minutes.",
      "Serve hot with naan or rice.",
    ],
    cuisine: "Indian",
  },
  {
    _id: "d357e5fb-9c65-4535-a463-97d11e61172d",
    id: 7,
    name: "Chole Bhature",
    ingredients: [
      "1 cup chickpeas, soaked overnight",
      "1 onion, finely chopped",
      "2 tomatoes, finely chopped",
      "2 cloves of garlic, minced",
      "1 tablespoon ginger paste",
      "2 green chilies, finely chopped",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "1 teaspoon coriander powder",
      "1 teaspoon garam masala",
      "1/2 teaspoon red chili powder",
      "Salt to taste",
      "Oil for deep frying",
      "Fresh cilantro for garnish",
    ],
    instructions: [
      "Cook the soaked chickpeas in a pressure cooker until soft. Drain and set aside.",
      "In a large pan, heat oil over medium heat for deep frying.",
      "Shape the dough into small balls and roll them into flat circles.",
      "Deep fry the bhature in the hot oil until they puff up and turn golden brown. Drain on paper towels.",
      "In a separate pan, heat oil over medium heat.",
      "Add the cumin seeds and sauté until they start to crackle.",
      "Add the chopped onion, minced garlic, and ginger paste. Sauté until the onion turns golden brown.",
      "Add the chopped tomatoes and cook until they soften.",
      "Stir in the turmeric powder, coriander powder, garam masala, red chili powder, and salt. Mix well.",
      "Add the cooked chickpeas and mix until they are coated with the spice mixture.",
      "Cover the pan and simmer for 10-15 minutes.",
      "Garnish with fresh cilantro before serving with hot bhature.",
    ],
    cuisine: "Indian",
  },
  {
    _id: "1e24f523-2395-445c-9cbc-dc2fdad1126a",
    id: 8,
    name: "Tandoori Chicken",
    ingredients: [
      "1 whole chicken, cut into pieces",
      "1 cup plain yogurt",
      "2 tablespoons lemon juice",
      "2 tablespoons tandoori masala",
      "1 tablespoon ginger paste",
      "1 tablespoon garlic paste",
      "1 teaspoon paprika",
      "1 teaspoon turmeric powder",
      "1 teaspoon garam masala",
      "1 teaspoon cumin powder",
      "Salt to taste",
      "Melted butter for basting",
      "Fresh cilantro for garnish",
    ],
    instructions: [
      "In a large bowl, combine the yogurt, lemon juice, tandoori masala, ginger paste, garlic paste, paprika, turmeric powder, garam masala, cumin powder, and salt.",
      "Add the chicken pieces to the bowl and coat them evenly with the marinade. Let the chicken marinate for at least 2 hours, preferably overnight in the refrigerator.",
      "Preheat the oven to 450°F (230°C).",
      "Place the marinated chicken pieces on a wire rack set over a baking sheet.",
      "Bake the chicken in the preheated oven for 25-30 minutes or until cooked through, turning once halfway through the cooking time.",
      "Baste the chicken with melted butter every 10 minutes for a juicy and flavorful result.",
      "Garnish with fresh cilantro before serving.",
    ],
    cuisine: "Indian",
  },
  {
    _id: "5d22596c-5b42-40ee-83b9-15190eae751c",
    id: 9,
    name: "Kung Pao Chicken",
    ingredients: [
      "500g boneless chicken, cut into cubes",
      "1/2 cup unsalted peanuts",
      "1/2 cup diced bell peppers",
      "1/2 cup diced onions",
      "2 cloves of garlic, minced",
      "1 tablespoon ginger paste",
      "2 tablespoons soy sauce",
      "1 tablespoon rice vinegar",
      "1 tablespoon hoisin sauce",
      "1 tablespoon cornstarch",
      "1 teaspoon sugar",
      "1/2 teaspoon red pepper flakes",
      "2 tablespoons vegetable oil",
      "Salt to taste",
      "Green onions for garnish",
    ],
    instructions: [
      "In a small bowl, whisk together the soy sauce, rice vinegar, hoisin sauce, cornstarch, sugar, and red pepper flakes. Set aside.",
      "Heat the vegetable oil in a large pan or wok over high heat.",
      "Add the minced garlic and ginger paste to the pan and stir-fry for about 30 seconds.",
      "Add the chicken cubes to the pan and stir-fry until they are cooked through and slightly browned.",
      "Add the diced bell peppers and onions to the pan and stir-fry for a few minutes until they are slightly softened.",
      "Pour the sauce mixture over the chicken and vegetables. Stir well to coat everything evenly.",
      "Add the unsalted peanuts and continue cooking for another minute.",
      "Season with salt to taste.",
      "Garnish with green onions before serving.",
    ],
    cuisine: "Chinese",
  },
  {
    _id: "993bbb1a-37ce-4c42-9548-5bf2ffc333d7",
    id: 10,
    name: "Egg Fried Rice",
    ingredients: [
      "3 cups cooked rice",
      "2 eggs, beaten",
      "1/2 cup frozen peas and carrots",
      "1/2 cup diced onions",
      "2 cloves of garlic, minced",
      "2 tablespoons soy sauce",
      "1 tablespoon oyster sauce",
      "1 tablespoon vegetable oil",
      "Salt and pepper to taste",
      "Green onions for garnish",
    ],
    instructions: [
      "Heat the vegetable oil in a large pan or wok over medium-high heat.",
      "Add the minced garlic and diced onions to the pan. Stir-fry for a few minutes until the onions become translucent.",
      "Push the onions and garlic to one side of the pan and pour the beaten eggs into the empty space.",
      "Scramble the eggs until they are fully cooked.",
      "Add the frozen peas and carrots to the pan and stir-fry for a few minutes until they are heated through.",
      "Add the cooked rice to the pan and break up any clumps with a spatula.",
      "Pour the soy sauce and oyster sauce over the rice. Stir well to coat everything evenly.",
      "Season with salt and pepper to taste.",
      "Continue cooking and stirring for a few more minutes until the rice is heated through.",
      "Garnish with green onions before serving.",
    ],
    cuisine: "Chinese",
  },
];
